<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.example</groupId><artifactId>cap-java-products-demo-parent</artifactId><version>1.0.0-SNAPSHOT</version>
  </parent>
  <artifactId>srv</artifactId>
  <dependencies>
    <dependency><groupId>com.sap.cds</groupId><artifactId>cds-starter-spring-boot-odata</artifactId></dependency>
    <dependency><groupId>com.h2database</groupId><artifactId>h2</artifactId><scope>runtime</scope></dependency>
    <dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-test</artifactId><scope>test</scope></dependency>
  </dependencies>
  <build><plugins>
    <plugin><groupId>org.springframework.boot</groupId><artifactId>spring-boot-maven-plugin</artifactId></plugin>
    <plugin>
      <groupId>com.sap.cds</groupId>
      <artifactId>cds-maven-plugin</artifactId>
      <version>${cds.services.version}</version>
      <executions>
        <execution>
          <goals><goal>generate</goal></goals>
        </execution>
        <execution>
          <id>h2-schema</id>
          <goals><goal>cds</goal></goals>
          <configuration>
            <commands>
              <command>deploy --to h2 --dry --out "${project.basedir}/src/main/resources/schema.sql"</command>
            </commands>
          </configuration>
        </execution>
      </executions>
    </plugin>
  </plugins></build>
</project>
